name: Linter pipeline
on:
  push:
    branches:
      - "!main"
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install angular cli
        run: npm install -g @angular/cli
      - name: Repository checkout
        uses: actions/checkout@v4
      - run: cd ${{ github.workspace }}
      - name: Run `npm install`
        run: npm install
      - name: Run linter
        run: ng lint
